### ISSUE TITLE
Improvement: make the server possible headless

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#34]
Currently the server is just run with java -jar gameserver.jar this creates the following headless exception on the server(only happens on command line machines)

```
Exception in thread "main" java.awt.HeadlessException:
No X11 DISPLAY variable was set, but this program performed an operation which requires it.
        at java.awt.GraphicsEnvironment.checkHeadless(GraphicsEnvironment.java:204)
        at java.awt.Window.<init>(Window.java:536)
        at java.awt.Frame.<init>(Frame.java:420)
        at javax.swing.JFrame.<init>(JFrame.java:233)
        at nl.hanze.gameserver.ui.GameServerGUI.createAndShowGui(GameServerGUI.java:35)
        at nl.hanze.gameserver.ui.GameServerGUI.<init>(GameServerGUI.java:31)
        at nl.hanze.gameserver.app.Application.<init>(Application.java:53)
        at nl.hanze.gameserver.app.Application.getInstance(Application.java:16)
        at nl.hanze.gameserver.app.Application.main(Application.java:138)
```

Maybe look into a way to launch in headless mode, commandline bases or a small rewrite

**Comment by goto-bus-stop** [comment]
via https://github.com/IcyPalm/Hanze-TwoPlayerGameServer/pull/35#issuecomment-208519076:

> Not sure if there's much of a future for this, because views are touched in a few places [and would require changes], and headless mode would miss a bunch of functionality. For the tournament, we may want to just run it on a local machine with a monitor(?)
