### ISSUE TITLE
Errors Galore!

### ISSUE THREAD

**Issue by IcyPalm** [IcyPalm/Hanze-TwoPlayerGameServer#39]
```
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at nl.hanze.gameserver.server.Client.writeLine(Client.java:129)
        at nl.hanze.gameserver.server.Client.writeResponse(Client.java:121)
        at nl.hanze.gameserver.server.command.MessageCommandHandler.handleCommand(MessageCommandHandler.java:41)
        at nl.hanze.gameserver.server.ClientInputHandler.run(ClientInputHandler.java:93)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "GameServer-Thread" java.lang.OutOfMemoryError: Java heap space
        at nl.hanze.gameserver.server.GameServer.handleRead(GameServer.java:161)
        at nl.hanze.gameserver.server.GameServer.run(GameServer.java:110)
        at java.lang.Thread.run(Thread.java:745)
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at nl.hanze.gameserver.server.Client.writeLine(Client.java:129)
        at nl.hanze.gameserver.server.Client.writeResponse(Client.java:121)
        at nl.hanze.gameserver.server.command.MessageCommandHandler.handleCommand(MessageCommandHandler.java:41)
        at nl.hanze.gameserver.server.ClientInputHandler.run(ClientInputHandler.java:93)
        at java.lang.Thread.run(Thread.java:745)
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at nl.hanze.gameserver.server.Client.writeLine(Client.java:129)
        at nl.hanze.gameserver.server.Client.writeResponse(Client.java:121)
        at nl.hanze.gameserver.server.command.MessageCommandHandler.handleCommand(MessageCommandHandler.java:41)
        at nl.hanze.gameserver.server.ClientInputHandler.run(ClientInputHandler.java:93)
        at java.lang.Thread.run(Thread.java:745)
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at nl.hanze.gameserver.server.Client.writeLine(Client.java:129)
        at nl.hanze.gameserver.server.Client.writeResponse(Client.java:121)
        at nl.hanze.gameserver.server.command.MessageCommandHandler.handleCommand(MessageCommandHandler.java:41)
        at nl.hanze.gameserver.server.ClientInputHandler.run(ClientInputHandler.java:93)
        at java.lang.Thread.run(Thread.java:745)
java.nio.BufferOverflowException
        at java.nio.DirectByteBuffer.put(DirectByteBuffer.java:363)
        at java.nio.ByteBuffer.put(ByteBuffer.java:859)
        at nl.hanze.gameserver.server.Client.writeLine(Client.java:129)
        at nl.hanze.gameserver.server.Client.writeResponse(Client.java:121)
        at nl.hanze.gameserver.server.command.MessageCommandHandler.handleCommand(MessageCommandHandler.java:41)
        at nl.hanze.gameserver.server.ClientInputHandler.run(ClientInputHandler.java:93)
        at java.lang.Thread.run(Thread.java:745)
Exception in thread "ClientInputHandler-Thread" java.lang.OutOfMemoryError: Java heap space
```

**Comment by goto-bus-stop** [comment]
![thinking_face](https://cloud.githubusercontent.com/assets/1006268/14532695/3cc74b96-0262-11e6-92ad-b4d8890c5665.png)
